services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai_agent_ses_postgre
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: red-ctqinttsvqrc73conufg
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker -l info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai_agent_ses_postgre
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: red-ctqinttsvqrc73conufg
          type: redis
          property: connectionString

  - type: redis
    name: red-ctqinttsvqrc73conufg
    ipAllowList: []
    plan: free

databases:
  - name: ai_agent_ses_postgre
    databaseName: ai_agent_ses_postgre
    user: japanmarketing
    plan: free
